### ISSUE TITLE
Build fails on communication-calling package

### ISSUE THREAD

**Issue by canperk** [Azure-Samples/communication-services-web-calling-hero#64] opened 2021-05-30 16:14 UTC
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>
node_modules/@azure/communication-calling/dist-esm/sdk.bundle.js:18:13900: error: Cannot assign to "i" because it is a constant
### Expected/desired behavior
> Project builds

### OS and Version?
> Windows 10

### Versions
> 1.0.0

### Mention any other details that might be useful

I created and with:

`npm init @vitejs/app peerque --template vue-ts` 

Then I added following packages to package.json to be able to test SDK functions.

```
    "@azure/communication-calling": "1.0.0",
    "@azure/communication-common": "1.0.0",
    "@azure/communication-identity": "1.0.0"
```

I have a simple page that imports `@azure/communication-calling` but when I try to build project it fails with error hat I wrote above. 

When I change `const` to `let` in the source code build passes. I don't know if it is related to my tsconfig.json or not. I will share it just in case.

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  "exclude": ["node_modules", "dist"]
}
```

Thanks in advance

**Comment by JamesBurnside** [comment] 2021-05-31 18:29
Followed the same steps and was able to repo.

Setup Steps:
```bash
> npm init @vitejs/app peerque --template vue-ts
> cd peerque
> npm i
> npm i @azure/communication-calling@1.0.0 @azure/communication-common@1.0.0 @azure/communication-identity@1.0.0
> npm run dev
```

Repro steps:
In `main.ts` add:
```typescript
import * as communication_calling from '@azure/communication-calling';
console.log(communication_calling);
```
Reload page.

Result:
```bash
11:12:15 a.m. [vite] new dependencies found: @azure/communication-calling, updating...
 > node_modules/@azure/communication-calling/dist-esm/sdk.bundle.js:18:13900: error: Cannot assign to "i" because it is a constant
    18 │ ...e),n=!1)},dispose:()=>{i=void 0}}}function asse...
       ╵                           ^
   node_modules/@azure/communication-calling/dist-esm/sdk.bundle.js:18:13765: note: "i" was declared a constant here
    18 │ ...r(){let e,t,n=!0;const i=new Promise(((n,i)=>{e...
       ╵                           ^
```

This is a bug in the [SDK](https://github.com/Azure/azure-sdk-for-js/) and not in the calling-sample (this repo).

Creating bug new bug in their repo...

**Comment by JamesBurnside** [comment] 2021-05-31 18:31
Issue created here https://github.com/Azure/azure-sdk-for-js/issues/15479, @canperk can you subscribe to notifications on this new issue and the corresponding team should follow up with you shortly.

Closing this as duplicate of the newly created issue https://github.com/Azure/azure-sdk-for-js/issues/15479.

**Closed by JamesBurnside** 2021-05-31 18:31 UTC
